# Generated by Django 6.0.4 on 2026-04-26 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="is_correct",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Правильно ли решено"
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="user_answer",
            field=models.TextField(blank=True, null=True, verbose_name="Ответ ученика"),
        ),
        migrations.AddField(
            model_name="task",
            name="fipi_id",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="ID задания ФИПИ"
            ),
        ),
    ]
