# Generated by Django 6.0.4 on 2026-04-26 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_submission_is_correct_submission_user_answer_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamFormat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Название формата (ЕГЭ/ОГЭ)"
                    ),
                ),
                ("year", models.IntegerField(verbose_name="Год экзамена")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Актуальный формат"),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_formats",
                        to="core.subject",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaskType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField(verbose_name="Номер в КИМе")),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="Краткое описание типа"
                    ),
                ),
                (
                    "max_points",
                    models.IntegerField(default=1, verbose_name="Максимальный балл"),
                ),
                (
                    "exam_format",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_types",
                        to="core.examformat",
                    ),
                ),
            ],
            options={
                "ordering": ["number"],
            },
        ),
        migrations.AddField(
            model_name="task",
            name="task_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="core.tasktype",
                verbose_name="Тип задания (КИМ)",
            ),
        ),
    ]
