# Generated by Django 6.0.4 on 2026-04-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_examformat_tasktype_task_task_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Ученик"),
                    ("tutor", "Репетитор"),
                    ("parent", "Родитель"),
                    ("admin", "Администратор"),
                    ("unassigned", "Не выбрана (из соцсети)"),
                ],
                default="unassigned",
                max_length=20,
            ),
        ),
    ]
