# Generated by Django 6.0.4 on 2026-04-26 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="subtype_tag",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Подтип/Тег математической логики",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="preferred_theme",
            field=models.CharField(
                choices=[
                    ("classic", "Классика"),
                    ("dota", "Dota 2"),
                    ("cs2", "CS2"),
                    ("ussr", "СССР"),
                ],
                default="classic",
                max_length=20,
                verbose_name="Предпочитаемая тема",
            ),
        ),
        migrations.CreateModel(
            name="TaskVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("classic", "Классика"),
                            ("dota", "Dota 2"),
                            ("cs2", "CS2"),
                            ("ussr", "СССР"),
                        ],
                        default="classic",
                        max_length=20,
                        verbose_name="Тема (Сеттинг)",
                    ),
                ),
                (
                    "content",
                    models.TextField(verbose_name="Условие задачи с учетом темы"),
                ),
                (
                    "solution",
                    models.TextField(
                        blank=True, null=True, verbose_name="Подробное решение"
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="core.task",
                    ),
                ),
            ],
            options={
                "unique_together": {("task", "theme")},
            },
        ),
    ]
