# Generated by Django 6.0.4 on 2026-04-26 14:44

from django.db import migrations

def migrate_content_to_variant(apps, schema_editor):
    Task = apps.get_model('core', 'Task')
    TaskVariant = apps.get_model('core', 'TaskVariant')

    for task in Task.objects.all():
        if task.content:
            TaskVariant.objects.get_or_create(
                task=task,
                theme='classic',
                defaults={
                    'content': task.content
                }
            )

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_task_subtype_tag_user_preferred_theme_taskvariant'),
    ]

    operations = [
        migrations.RunPython(migrate_content_to_variant),
    ]
