# Generated by Django 6.0.4 on 2026-04-26 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_migrate_task_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="content",
        ),
    ]
