# Generated by Django 6.0.4 on 2026-04-26 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_remove_task_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="current_streak",
        ),
        migrations.RemoveField(
            model_name="user",
            name="level",
        ),
        migrations.RemoveField(
            model_name="user",
            name="parents",
        ),
        migrations.RemoveField(
            model_name="user",
            name="target_score",
        ),
        migrations.RemoveField(
            model_name="user",
            name="tutors",
        ),
        migrations.RemoveField(
            model_name="user",
            name="xp",
        ),
        migrations.AddField(
            model_name="user",
            name="invite_code",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                unique=True,
                verbose_name="Код-приглашение",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="role_assigned_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата назначения роли (для триала)"
            ),
        ),
        migrations.CreateModel(
            name="TutorStudentLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "target_score",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Целевой балл"
                    ),
                ),
                ("xp", models.IntegerField(default=0, verbose_name="Опыт (XP)")),
                ("level", models.IntegerField(default=1, verbose_name="Уровень")),
                (
                    "current_streak",
                    models.IntegerField(default=0, verbose_name="Стрик (дней)"),
                ),
                (
                    "parents",
                    models.ManyToManyField(
                        blank=True,
                        limit_choices_to={"role": "parent"},
                        related_name="children",
                        to="core.tutorstudentlink",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linked_tutors",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Ученик",
                    ),
                ),
                (
                    "tutor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linked_students",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Репетитор",
                    ),
                ),
                (
                    "tutors",
                    models.ManyToManyField(
                        blank=True,
                        limit_choices_to={"role": "tutor"},
                        related_name="students",
                        to="core.tutorstudentlink",
                    ),
                ),
            ],
            options={
                "verbose_name": "Связь Репетитор-Ученик",
                "verbose_name_plural": "Связи Репетитор-Ученик",
                "unique_together": {("tutor", "student")},
            },
        ),
    ]
