# Generated by Django 6.0.4 on 2026-04-26 19:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_remove_user_current_streak_remove_user_level_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tutorstudentlink",
            name="current_streak",
        ),
        migrations.RemoveField(
            model_name="tutorstudentlink",
            name="level",
        ),
        migrations.RemoveField(
            model_name="tutorstudentlink",
            name="parents",
        ),
        migrations.RemoveField(
            model_name="tutorstudentlink",
            name="target_score",
        ),
        migrations.RemoveField(
            model_name="tutorstudentlink",
            name="tutors",
        ),
        migrations.RemoveField(
            model_name="tutorstudentlink",
            name="xp",
        ),
        migrations.AddField(
            model_name="user",
            name="current_streak",
            field=models.IntegerField(default=0, verbose_name="Стрик (дней)"),
        ),
        migrations.AddField(
            model_name="user",
            name="level",
            field=models.IntegerField(default=1, verbose_name="Уровень"),
        ),
        migrations.AddField(
            model_name="user",
            name="parents",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"role": "parent"},
                related_name="children",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="target_score",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Целевой балл"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="tutors",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"role": "tutor"},
                related_name="students",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="xp",
            field=models.IntegerField(default=0, verbose_name="Опыт (XP)"),
        ),
    ]
