# Generated by Django 6.0.4 on 2026-04-27 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_assignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="is_draft",
            field=models.BooleanField(
                default=False, verbose_name="Черновик (на стадии сборки)"
            ),
        ),
    ]
