# Generated by Django 6.0.4 on 2026-04-27 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_assignment_is_draft"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="assignment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to="core.assignment",
                verbose_name="Вариант (если решалось в рамках варианта)",
            ),
        ),
    ]
