# Generated by Django 6.0.4 on 2026-04-27 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_submission_assignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="parent_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Имя родителя"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="parent_phone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Телефон родителя"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="tutor_notes",
            field=models.TextField(
                blank=True, null=True, verbose_name="Заметки репетитора"
            ),
        ),
    ]
