# Generated by Django 6.0.4 on 2026-04-27 08:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_user_parent_name_user_parent_phone_user_tutor_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="primary_score",
            field=models.IntegerField(
                default=0, verbose_name="Первичный балл (развернутая часть)"
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="requires_draft",
            field=models.BooleanField(
                default=False, verbose_name="Был запрошен черновик"
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="upload_token",
            field=models.UUIDField(
                blank=True,
                default=uuid.uuid4,
                null=True,
                verbose_name="Токен для загрузки фото",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="draft_check_probability",
            field=models.IntegerField(
                default=0, verbose_name="Вероятность запроса черновика (%)"
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="image_url",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="submissions/",
                verbose_name="Фото решения/черновика",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="score",
            field=models.IntegerField(default=0, verbose_name="Начисленный балл"),
        ),
        migrations.AlterField(
            model_name="submission",
            name="user_answer",
            field=models.TextField(
                blank=True, null=True, verbose_name="Текстовый ответ ученика"
            ),
        ),
    ]
