# Generated by Django 6.0.4 on 2026-04-27 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_submission_primary_score_submission_requires_draft_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Система и API",
                "verbose_name_plural": "Система и API",
                "managed": False,
            },
        ),
        migrations.RemoveField(
            model_name="payment",
            name="paid_at",
        ),
        migrations.AlterField(
            model_name="payment",
            name="lessons_credited",
            field=models.IntegerField(default=1, verbose_name="Количество занятий"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="parent",
            field=models.ForeignKey(
                limit_choices_to={"role": "parent"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments_made",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Родитель",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[("pending", "В обработке"), ("completed", "Оплачено")],
                default="pending",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="student",
            field=models.ForeignKey(
                limit_choices_to={"role": "student"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments_received",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Ученик",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="tutor",
            field=models.ForeignKey(
                limit_choices_to={"role": "tutor"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments_collected",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Репетитор",
            ),
        ),
    ]
