# Generated by Django 6.0.4 on 2026-04-27 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_systemconfig_remove_payment_paid_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentSubjectProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_score",
                    models.IntegerField(default=80, verbose_name="Целевой балл"),
                ),
                ("xp", models.IntegerField(default=0, verbose_name="Опыт (XP)")),
                ("level", models.IntegerField(default=1, verbose_name="Уровень")),
                (
                    "current_streak",
                    models.IntegerField(default=0, verbose_name="Стрик (дней)"),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_profiles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Ученик",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.subject",
                        verbose_name="Предмет",
                    ),
                ),
            ],
            options={
                "verbose_name": "Профиль ученика по предмету",
                "verbose_name_plural": "Профили учеников по предметам",
                "unique_together": {("student", "subject")},
            },
        ),
    ]
