# Generated by Django 6.0.4 on 2026-04-27 11:57

from django.db import migrations

def move_user_stats_to_profile(apps, schema_editor):
    User = apps.get_model('core', 'User')
    Subject = apps.get_model('core', 'Subject')
    StudentSubjectProfile = apps.get_model('core', 'StudentSubjectProfile')

    # Get or create default subject
    math_subject, _ = Subject.objects.get_or_create(name='Математика (Профиль)')

    # Move data for all students
    for student in User.objects.filter(role='student'):
        StudentSubjectProfile.objects.get_or_create(
            student=student,
            subject=math_subject,
            defaults={
                'target_score': student.target_score or 80,
                'xp': student.xp,
                'level': student.level,
                'current_streak': student.current_streak,
            }
        )

def reverse_move(apps, schema_editor):
    # Backward migration is tricky because we might have multiple subjects now.
    # We will just copy Math stats back to User if we ever rollback.
    User = apps.get_model('core', 'User')
    Subject = apps.get_model('core', 'Subject')
    StudentSubjectProfile = apps.get_model('core', 'StudentSubjectProfile')

    try:
        math_subject = Subject.objects.get(name='Математика (Профиль)')
        for profile in StudentSubjectProfile.objects.filter(subject=math_subject):
            student = profile.student
            student.target_score = profile.target_score
            student.xp = profile.xp
            student.level = profile.level
            student.current_streak = profile.current_streak
            student.save()
    except Subject.DoesNotExist:
        pass

class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_studentsubjectprofile"),
    ]

    operations = [
        migrations.RunPython(move_user_stats_to_profile, reverse_move),
    ]
