# Generated by Django 6.0.4 on 2026-04-27 13:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_migrate_user_xp_to_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="is_verified",
            field=models.BooleanField(
                default=False, verbose_name="Контрольная работа (Verified Mode)"
            ),
        ),
        migrations.AddField(
            model_name="studentsubjectprofile",
            name="avg_model_error",
            field=models.FloatField(
                default=0.0, verbose_name="Средняя ошибка модели прогноза"
            ),
        ),
        migrations.AddField(
            model_name="studentsubjectprofile",
            name="last_verified_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата последней верификации"
            ),
        ),
        migrations.AddField(
            model_name="studentsubjectprofile",
            name="learning_velocity",
            field=models.FloatField(
                default=1.0, verbose_name="Коэффициент обучаемости (Темп)"
            ),
        ),
        migrations.AddField(
            model_name="studentsubjectprofile",
            name="trust_factor",
            field=models.FloatField(
                default=0.6, verbose_name="Индекс доверия (0.0 - 1.0)"
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="primary_score",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Первичный балл (0-4)"
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="score",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Итоговый балл за решение (для 2 части)",
            ),
        ),
        migrations.CreateModel(
            name="TaskLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "time_spent",
                    models.IntegerField(
                        default=0, verbose_name="Потрачено времени (секунд)"
                    ),
                ),
                (
                    "score",
                    models.FloatField(default=0.0, verbose_name="Полученный балл"),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False, verbose_name="Была ли это контрольная (Verified)"
                    ),
                ),
                (
                    "verifier_role",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Кто верифицировал (tutor/parent)",
                    ),
                ),
                (
                    "is_anomaly",
                    models.BooleanField(
                        default=False,
                        verbose_name="Аномалия (слишком быстро/списывание)",
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="task_logs",
                        to="core.assignment",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="task_logs",
                        to="core.submission",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.task"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DailySnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "current_mastery",
                    models.FloatField(
                        default=0.0, verbose_name="Текущее мастерство (0-100)"
                    ),
                ),
                (
                    "predicted_exam_score",
                    models.FloatField(default=0.0, verbose_name="Прогноз балла на ЕГЭ"),
                ),
                (
                    "gap_between_solo_and_verified",
                    models.FloatField(
                        default=0.0, verbose_name="Разрыв между Solo и Verified"
                    ),
                ),
                (
                    "rolling_forecast_error",
                    models.FloatField(
                        default=0.0, verbose_name="Скользящая ошибка прогноза"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.subject"
                    ),
                ),
            ],
            options={
                "verbose_name": "Ежедневный срез аналитики",
                "verbose_name_plural": "Ежедневные срезы аналитики",
                "unique_together": {("student", "subject", "date")},
            },
        ),
    ]
