# Generated by Django 6.0.4 on 2026-04-27 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasklog",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_logs",
                to="core.task",
            ),
        ),
    ]
