# Generated by Django 6.0.4 on 2026-04-29 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_alter_tasklog_task"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskGenerationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(default="openrouter", max_length=50)),
                ("model", models.CharField(blank=True, max_length=200, null=True)),
                ("mode", models.CharField(default="full", max_length=50)),
                ("prompt_template", models.TextField(blank=True, null=True)),
                ("prompt_rendered", models.TextField(blank=True, null=True)),
                ("response_raw", models.TextField(blank=True, null=True)),
                ("result_content_html", models.TextField(blank=True, null=True)),
                ("result_solution_html", models.TextField(blank=True, null=True)),
                ("result_correct_answer", models.TextField(blank=True, null=True)),
                ("status", models.CharField(default="success", max_length=20)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generation_logs",
                        to="core.task",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_generation_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
