# Generated by Django 6.0.4 on 2026-05-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_openroutermodel_subjectaiconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="parent_invite_code",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                unique=True,
                verbose_name="Код для привязки родителя",
            ),
        ),
    ]

