# Generated by Django 6.0.4 on 2026-05-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_user_parent_invite_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="ui_theme",
            field=models.CharField(
                choices=[
                    ("light", "Классическая белая"),
                    ("dark", "Тёмная"),
                    ("dark_classic", "Классическая чёрная"),
                ],
                default="light",
                max_length=20,
                verbose_name="Тема интерфейса",
            ),
        ),
    ]

