# Generated by Django 6.0.4 on 2026-05-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_update_oge_math_tasktype_names"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="ai_mistakes_json",
            field=models.TextField(
                blank=True, null=True, verbose_name="ИИ: ошибки (JSON-массив строк)"
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="ai_recognized_solution",
            field=models.TextField(
                blank=True, null=True, verbose_name="ИИ: распознанное решение (текст)"
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="ai_verdict_json",
            field=models.TextField(
                blank=True, null=True, verbose_name="ИИ: вердикт (JSON-массив абзацев)"
            ),
        ),
    ]
