# Generated by Django 6.0.4 on 2026-05-10 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_whiteboard_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="due_date",
            field=models.DateField(blank=True, null=True, verbose_name="Срок (до конца дня)"),
        ),
        migrations.AddField(
            model_name="assignment",
            name="expired_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Когда просрочено"),
        ),
        migrations.AddField(
            model_name="assignment",
            name="is_expired",
            field=models.BooleanField(default=False, verbose_name="Просрочено (автозакрыто)"),
        ),
        migrations.CreateModel(
            name="AssignmentExtensionRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("requested_days", models.PositiveIntegerField()),
                ("comment", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Ожидает"), ("approved", "Одобрено"), ("rejected", "Отклонено")],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extension_requests",
                        to="core.assignment",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extension_requests_as_student",
                        to="core.user",
                    ),
                ),
                (
                    "tutor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extension_requests_as_tutor",
                        to="core.user",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]

