# Generated by Django 5.2.1 on 2026-05-11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_task_bundle_code"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SubmissionComment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("author_role", models.CharField(choices=[("student", "Ученик"), ("tutor", "Репетитор")], max_length=20)),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="submission_comments", to=settings.AUTH_USER_MODEL),
                ),
                (
                    "submission",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="comments", to="core.submission"),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="submissioncomment",
            index=models.Index(fields=["submission", "created_at"], name="core_submitm_submiss_56d497_idx"),
        ),
    ]

