# Generated by Django 6.0.4 on 2026-05-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_submissioncomment"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="submissioncomment",
            new_name="core_submis_submiss_02e47f_idx",
            old_name="core_submitm_submiss_56d497_idx",
        ),
        migrations.RenameIndex(
            model_name="whiteboardsession",
            new_name="core_whiteb_student_5cdef5_idx",
            old_name="wb_session_student_task_idx",
        ),
        migrations.AddField(
            model_name="submissioncomment",
            name="seen_by_student_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="submissioncomment",
            name="seen_by_tutor_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
