# Generated by Django 6.0.4 on 2026-05-11 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0034_rename_core_submitm_submiss_56d497_idx_core_submis_submiss_02e47f_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="exam_format",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assignments",
                to="core.examformat",
            ),
        ),
        migrations.AddField(
            model_name="studentsubjectprofile",
            name="exam_format",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="student_profiles",
                to="core.examformat",
            ),
        ),
    ]
