# Generated by Django 6.0.4 on 2026-05-11 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_assignment_exam_format_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentsubjectprofile",
            name="last_streak_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата последнего дня стрика"
            ),
        ),
    ]
