# Generated by Django 6.0.4 on 2026-05-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0037_tutorreward"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentsubjectprofile",
            name="exam_date",
            field=models.DateField(blank=True, null=True, verbose_name="Дата экзамена"),
        ),
    ]
