# Generated by Django 6.0.4 on 2026-05-13 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0042_update_oge_math_tasktype_points"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="kind",
            field=models.CharField(
                blank=True,
                choices=[
                    ("homework", "Домашняя работа"),
                    ("test", "Тест"),
                    ("control_test", "Контрольный тест"),
                ],
                max_length=32,
                null=True,
                verbose_name="Тип варианта",
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="student_seq",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Порядковый номер по ученику"
            ),
        ),
    ]
