# Generated by Django 6.0.4 on 2026-05-13 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0043_assignment_kind_assignment_student_seq"),
    ]

    operations = [
        migrations.AddField(
            model_name="subjectaiconfig",
            name="photo_compare_model_1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.openroutermodel",
            ),
        ),
        migrations.AddField(
            model_name="subjectaiconfig",
            name="photo_compare_model_2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.openroutermodel",
            ),
        ),
        migrations.AddField(
            model_name="subjectaiconfig",
            name="photo_compare_model_3",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.openroutermodel",
            ),
        ),
        migrations.AddField(
            model_name="subjectaiconfig",
            name="photo_compare_model_4",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.openroutermodel",
            ),
        ),
        migrations.AddField(
            model_name="subjectaiconfig",
            name="photo_compare_model_5",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.openroutermodel",
            ),
        ),
    ]
