# Generated by Django 6.0.4 on 2026-05-13 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0044_subjectaiconfig_photo_compare_model_1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasktype",
            name="is_extended_answer",
            field=models.BooleanField(
                default=False, verbose_name="Развёрнутый ответ (требует фото)"
            ),
        ),
    ]
