# Generated by Django 6.0.4 on 2026-05-13 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0047_backfill_extended_answer_by_subject_and_format"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="show_solution_allowed",
            field=models.BooleanField(
                default=False, verbose_name="Разрешено показывать решение ученику"
            ),
        ),
    ]
