# Generated by Django 6.0.4 on 2026-05-15 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0053_assignment_soft_delete"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="ai_mistakes_json",
            field=models.TextField(
                blank=True, null=True, verbose_name="ИИ: ошибки (JSON-массив строк)"
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="ai_recognized_solution",
            field=models.TextField(
                blank=True, null=True, verbose_name="ИИ: распознанное решение (текст)"
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="ai_verdict_json",
            field=models.TextField(
                blank=True, null=True, verbose_name="ИИ: вердикт (JSON-массив абзацев)"
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="image_url",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="submissions/",
                verbose_name="Фото решения/черновика (стр. 1)",
            ),
        ),
    ]
