# Generated by Django 6.0.4 on 2026-05-14 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0053_assignment_soft_delete"),
    ]

    operations = [
        migrations.AddField(
            model_name="whiteboardsession",
            name="ai_feedback",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="whiteboardsession",
            name="ai_last_verify_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="whiteboardsession",
            name="ai_max_score",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="whiteboardsession",
            name="ai_score",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="whiteboardsession",
            name="ai_verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="whiteboard_ai_verified",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
