# Generated by Django 6.0.4 on 2026-05-15 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0054_submission_ai_mistakes_json_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="ai_annotated_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="ИИ: размечено"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="ai_annotation_version",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="ИИ: версия разметки"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="ai_difficulty_exam_percentile",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="ИИ: сложность (процентиль по экзамену)",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="ai_difficulty_raw",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="ИИ: сложность (1-100)"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="ai_difficulty_type_percentile",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="ИИ: сложность (процентиль по типу)"
            ),
        ),
        migrations.CreateModel(
            name="TaskTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("method", "Метод"),
                            ("property", "Свойство"),
                            ("topic", "Тема"),
                            ("other", "Другое"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["kind", "name"], name="core_taskta_kind_b6e201_idx"
                    )
                ],
                "unique_together": {("kind", "name")},
            },
        ),
        migrations.AddField(
            model_name="task",
            name="ai_tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="tasks",
                to="core.tasktag",
                verbose_name="ИИ: теги",
            ),
        ),
    ]
