# Generated by Django 6.0.4 on 2026-05-16 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0056_seed_oge_physics_2026_tasktypes"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="learning_velocity_calibrated_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Когда калибровали learning_velocity по этому варианту",
            ),
        ),
        migrations.AlterField(
            model_name="tasktype",
            name="is_extended_answer",
            field=models.BooleanField(
                default=False, verbose_name="Развёрнутый ответ (часть 2)"
            ),
        ),
    ]
