# Generated by Django 6.0.4 on 2026-05-18 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0057_learning_velocity_calibrated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="spacedrepetition",
            name="last_reviewed_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
