# Generated by Django 6.0.4 on 2026-05-18 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0058_spacedrepetition_last_reviewed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="ai_photo_valid",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="ИИ: фото валидно ли для этой задачи"
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="ai_photo_valid_reason",
            field=models.TextField(
                blank=True, null=True, verbose_name="ИИ: причина невалидного фото"
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="ai_recognition_confidence",
            field=models.FloatField(
                blank=True, null=True, verbose_name="ИИ: уверенность распознавания (0..1)"
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="ai_score_breakdown_json",
            field=models.TextField(
                blank=True, null=True, verbose_name="ИИ: снятие баллов (JSON-массив объектов)"
            ),
        ),
    ]

