# Generated by Django 6.0.4 on 2026-06-14 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0068_schooltaskmeta_ai_provenance"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskAudioAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("reshuege", "РешуОГЭ/ЕГЭ")], max_length=32
                    ),
                ),
                ("original_url", models.URLField(max_length=1000)),
                ("file", models.FileField(upload_to="tasks/audio/")),
                ("sha256", models.CharField(max_length=64)),
                ("mime_type", models.CharField(blank=True, default="", max_length=128)),
                ("size_bytes", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="TaskContextGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("reshuege", "РешуОГЭ/ЕГЭ")], max_length=32
                    ),
                ),
                ("group_key", models.CharField(max_length=1000)),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                (
                    "position_hint",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name="taskaudioasset",
            constraint=models.UniqueConstraint(
                fields=("source", "original_url"),
                name="uniq_task_audio_asset_source_url",
            ),
        ),
        migrations.AddConstraint(
            model_name="taskaudioasset",
            constraint=models.UniqueConstraint(
                fields=("source", "sha256"), name="uniq_task_audio_asset_source_sha256"
            ),
        ),
        migrations.AddField(
            model_name="taskcontextgroup",
            name="audio_asset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="context_groups",
                to="core.taskaudioasset",
            ),
        ),
        migrations.AddField(
            model_name="taskcontextgroup",
            name="exam_format",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="task_context_groups",
                to="core.examformat",
            ),
        ),
        migrations.AddField(
            model_name="taskcontextgroup",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_context_groups",
                to="core.subject",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="context_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="core.taskcontextgroup",
            ),
        ),
        migrations.AddConstraint(
            model_name="taskcontextgroup",
            constraint=models.UniqueConstraint(
                fields=("source", "group_key"),
                name="uniq_task_context_group_source_key",
            ),
        ),
    ]
