# Generated by Django 6.0.4 on 2026-06-22 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0069_task_audio_groups"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="spacedrepetitionremovalrequest",
            new_name="core_spaced_tutor_i_0300bc_idx",
            old_name="core_spaced_tutor_srs_idx",
        ),
        migrations.RenameIndex(
            model_name="spacedrepetitionremovalrequest",
            new_name="core_spaced_student_b1ecd6_idx",
            old_name="core_spaced_student_srs_idx",
        ),
        migrations.AddField(
            model_name="tasktype",
            name="explanation",
            field=models.TextField(
                blank=True, default="", verbose_name="Пояснение (RU)"
            ),
        ),
        migrations.AddField(
            model_name="tasktype",
            name="explanation_en",
            field=models.TextField(
                blank=True, default="", verbose_name="Пояснение (EN)"
            ),
        ),
    ]
